"""unique fields

Revision ID: 2434e460b6c7
Revises: 383ea07e05a1
Create Date: 2026-05-20 19:00:34.317858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2434e460b6c7'
down_revision: Union[str, Sequence[str], None] = '383ea07e05a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_types_name'), table_name='product_types')
    op.create_index(op.f('ix_product_types_name'), 'product_types', ['name'], unique=True)
    op.create_unique_constraint(None, 'products', ['name', 'product_type_id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index(op.f('ix_product_types_name'), table_name='product_types')
    op.create_index(op.f('ix_product_types_name'), 'product_types', ['name'], unique=False)
    # ### end Alembic commands ###
