"""add description image_url to products

Revision ID: a08aaf9d185e
Revises: 2434e460b6c7
Create Date: 2026-05-25 07:26:10.216025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08aaf9d185e'
down_revision: Union[str, Sequence[str], None] = '2434e460b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
