"""Null fields

Revision ID: c875afb1660e
Revises: f0ca0a05df3a
Create Date: 2026-04-26 17:11:28.691703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c875afb1660e'
down_revision: Union[str, Sequence[str], None] = 'f0ca0a05df3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'delivery_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'delivery_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
